name: Build EXE

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow tkinterdnd2 pyinstaller

      - name: Extract version from tag
        id: vars
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed image_to_webp.pyw

      - name: Rename output
        run: move dist\\image_to_webp.exe dist\\EasyWebPConverter-${{ env.VERSION }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EasyWebPConverter-${{ env.VERSION }}
          path: dist/EasyWebPConverter-${{ env.VERSION }}.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/EasyWebPConverter-${{ env.VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
