name: Build and Release EasyWebPConverter

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pillow tkinterdnd2 pyinstaller

      - name: Extract version from tag
        id: version
        run: |
          $tag = "${{ github.ref }}".Split("/")[-1] -replace "^v", ""
          $tuple = $tag.Split(".") + @(0,0,0,0) | Select-Object -First 4
          $tuple = $tuple -join ", "
          $template = Get-Content version_template.txt -Raw
          $template = $template -replace "{{VER_STRING}}", "$tag"
          $template = $template -replace "{{VER_TUPLE}}", $tuple
          Set-Content version.txt $template -Encoding UTF8
        shell: pwsh

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --icon=ewc.ico --name EasyWebPConverter --version-file=version.txt image_to_webp.pyw

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/EasyWebPConverter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
